site_name: Персональный сайт | Плотникова Виктория
site_description: Персональный сайт, созданный с использованием технологии MkDocs и языка разметки Markdown в рамках курсовой работы по предмету "Введение в веб технологии"
site_author: Виктория Плотникова
site_url: https://viktoryplo.github.io/2025_2026-introduction-in-web-tech-u4125-plotnikova_v_a/

theme:
  name: material
  language: ru
  icon:
    logo: fontawesome/solid/star
    favicon: fontawesome/solid/star
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - navigation.expand
    - content.code.copy
  palette:
    primary: pink
    accent: pink

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search

nav:
  - Главная: index.md
  - О себе: about.md
  - Проекты: projects.md
  - Достижения: achievements.md
  - Контакты: contacts.md

copyright: Copyright &copy; 2026 Виктория Плотникова

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/v5plo
      name: Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/viktoryplo
      name: GitHub